name: Zadanie 5 - Automatyzacja Terraform

on:
  workflow_dispatch:

jobs:
  Terraform_Orchestration:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Zalogowanie do chmury Azure
        # Używamy oficjalnej akcji od Microsoftu i naszego Service Principal (z Zadania 3)
        uses: azure/login@v2
        with:
          creds: {
            "id": ${{ secrets.AZURE_USERNAME }},
            "password": ${{ secrets.AZURE_PASSWORD }},
            "tenantId": ${{ secrets.AZURE_TENANT_ID }},
            "subscriptionId": "1eda8a5b-beaf-4dee-ad9f-8775bf41a043"
          }

      - name: Instalacja i konfiguracja Terraforma
        uses: hashicorp/setup-terraform@v3

      - name: Inicjalizacja środowiska
        run: terraform init
        working-directory: ./terraform
        # UWAGA: Używamy stanu lokalnego ze względu na limit czasu zajęć (2.5h). 
        # W środowisku produkcyjnym MUST HAVE: 'backend "azurerm"' w pliku TF i Azure Blob Storage!

      - name: Walidacja kodu (Formatowanie)
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Budowa infrastruktury
        run: terraform apply -auto-approve
        working-directory: ./terraform